S3_BUCKET: utd-catalog-tokenaughts
S3_PREFIX: catalog/
TITAN_MODEL_ID: amazon.titan-embed-text-v2:0

PINECONE_INDEX: utdcatalog
PINECONE_CLOUD: aws
PINECONE_REGION: us-east-1
CHUNK_SIZE: 2000
OVERLAP: 200
EMBED_BATCH: 32
TITAN_DIM: 1024

